# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for Bun/Vite frontend (uses npm ecosystem)
  - package-ecosystem: "npm"
    directory: "/" # package.json is at the root
    schedule:
      interval: "weekly"

  # Configuration for Rust backend
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
